services:
  postgres:
    restart: unless-stopped

  adminapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: unless-stopped

  scheduler:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: unless-stopped

  telegrambot:
    environment:
      DOTNET_ENVIRONMENT: Production
    restart: unless-stopped

  frontend:
    restart: unless-stopped
    ports:
      - "80:80"