// <auto-generated />
using System;
using Infrastructure.Foundation.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BuddyBotDbContext))]
    [Migration("20250707124348_StoreProcessKindAsString")]
    partial class StoreProcessKindAsString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AccountCreationToken", b =>
                {
                    b.Property<Guid>("TokenValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QrCodeBase64")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramInviteLink")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TokenValue");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.HasIndex("CreatorId");

                    b.ToTable("AccountCreationToken", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CandidateProcess", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessKind")
                        .HasColumnType("text");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("CandidateId", "ProcessKind");

                    b.ToTable("CandidateProcess", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HeadFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HeadLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HeadMicrosoftTeamsUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HeadVideoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HRInfo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("HRInfo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OnboardingAccessRequest", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestOutcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CandidateId");

                    b.ToTable("OnboardingAccessRequest", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<string>("PermissionName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PermissionName");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionName = "AccountCreationTokenView",
                            Description = "Просмотр токенов для создания кандидатов"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenCreate",
                            Description = "Генерация токена для создания кандидата"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenUpdate",
                            Description = "Редактирование токена для создание кандидата"
                        },
                        new
                        {
                            PermissionName = "CandidateView",
                            Description = "Просмотр кандидатов"
                        },
                        new
                        {
                            PermissionName = "CandidateCreate",
                            Description = "Создание кандидата"
                        },
                        new
                        {
                            PermissionName = "CandidateUpdate",
                            Description = "Обновление данных кандидата"
                        },
                        new
                        {
                            PermissionName = "CityView",
                            Description = "Просмотр городов"
                        },
                        new
                        {
                            PermissionName = "CityCreate",
                            Description = "Создание города"
                        },
                        new
                        {
                            PermissionName = "CityUpdate",
                            Description = "Редактирование города"
                        },
                        new
                        {
                            PermissionName = "CityDelete",
                            Description = "Удаление города"
                        },
                        new
                        {
                            PermissionName = "CountryView",
                            Description = "Просмотр стран"
                        },
                        new
                        {
                            PermissionName = "CountryCreate",
                            Description = "Создание страны"
                        },
                        new
                        {
                            PermissionName = "CountryUpdate",
                            Description = "Редактирование страны"
                        },
                        new
                        {
                            PermissionName = "CountryDelete",
                            Description = "Удаление страны"
                        },
                        new
                        {
                            PermissionName = "DepartmentView",
                            Description = "Просмотр отделов"
                        },
                        new
                        {
                            PermissionName = "DepartmentCreate",
                            Description = "Создание отдела"
                        },
                        new
                        {
                            PermissionName = "DepartmentUpdate",
                            Description = "Редактирование отдела"
                        },
                        new
                        {
                            PermissionName = "DepartmentDelete",
                            Description = "Удаление отдела"
                        },
                        new
                        {
                            PermissionName = "FeedbackView",
                            Description = "Просмотр отзывов"
                        },
                        new
                        {
                            PermissionName = "FeedbackCreate",
                            Description = "Добавление отзыва"
                        },
                        new
                        {
                            PermissionName = "FeedbackDelete",
                            Description = "Удаление отзыва"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestView",
                            Description = "Просмотр заявок на доступ к онбордингу"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestCreate",
                            Description = "Создание заявки на доступ к онбордингу"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestConfirm",
                            Description = "Подтверждение заявки на доступ к онбордингу"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestReject",
                            Description = "Отклонение заявки на доступ К онбордингу"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestUpdate",
                            Description = "Обновление данных заявки на доступ к онбординге"
                        },
                        new
                        {
                            PermissionName = "TeamView",
                            Description = "Просмотр команд"
                        },
                        new
                        {
                            PermissionName = "TeamCreate",
                            Description = "Создание команды"
                        },
                        new
                        {
                            PermissionName = "UserRegister",
                            Description = "Регистрация пользователя"
                        },
                        new
                        {
                            PermissionName = "UserLogin",
                            Description = "Вход пользователя"
                        },
                        new
                        {
                            PermissionName = "UserRefreshToken",
                            Description = "Обновление токена доступа"
                        },
                        new
                        {
                            PermissionName = "UserCreateHR",
                            Description = "Создание HR-пользователя"
                        },
                        new
                        {
                            PermissionName = "UserCreateMentor",
                            Description = "Создание наставника"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.HasKey("RoleName");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleName = "HR"
                        },
                        new
                        {
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            RoleName = "Mentor"
                        },
                        new
                        {
                            RoleName = "Candidate"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("LeaderId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LeaderId");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("OnboardingAccessTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasFilter("\"Login\" IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserAuthToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserId");

                    b.ToTable("UserAuthToken", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserContactInfo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MentorPhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MentorVideoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MicrosoftTeamsUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TelegramContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("CityId");

                    b.ToTable("UserContactInfo", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionName")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.HasKey("PermissionName", "RoleName");

                    b.HasIndex("RoleName");

                    b.ToTable("PermissionRole");

                    b.HasData(
                        new
                        {
                            PermissionName = "AccountCreationTokenView",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenCreate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenUpdate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CandidateView",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CandidateCreate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CandidateUpdate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CityView",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CityCreate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CityUpdate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CityDelete",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CountryView",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CountryCreate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CountryUpdate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "CountryDelete",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "DepartmentView",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "DepartmentCreate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "DepartmentUpdate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "DepartmentDelete",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "FeedbackView",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "FeedbackCreate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "FeedbackDelete",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestView",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestCreate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestConfirm",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestReject",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestUpdate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "TeamView",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "TeamCreate",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "UserRegister",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "UserLogin",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "UserRefreshToken",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "UserCreateHR",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "UserCreateMentor",
                            RoleName = "Admin"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenView",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenCreate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenUpdate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CandidateView",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CandidateCreate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CandidateUpdate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CityView",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CityCreate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CityUpdate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CityDelete",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CountryView",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CountryCreate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CountryUpdate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "CountryDelete",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "DepartmentView",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "DepartmentCreate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "DepartmentUpdate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "DepartmentDelete",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "FeedbackView",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "FeedbackCreate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "FeedbackDelete",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestView",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestCreate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestConfirm",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestReject",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestUpdate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "TeamView",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "TeamCreate",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "UserRegister",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "UserLogin",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "UserRefreshToken",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "UserCreateHR",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "UserCreateMentor",
                            RoleName = "SuperHR"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenView",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenCreate",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "AccountCreationTokenUpdate",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "CandidateView",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "CandidateCreate",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "CandidateUpdate",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "CityView",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "CountryView",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "DepartmentView",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "FeedbackView",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestView",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestCreate",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestConfirm",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestReject",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "OnboardingAccessRequestUpdate",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "TeamView",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "UserLogin",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "UserRefreshToken",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "UserCreateMentor",
                            RoleName = "HR"
                        },
                        new
                        {
                            PermissionName = "CandidateView",
                            RoleName = "Mentor"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesRoleName")
                        .HasColumnType("text");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("RolesRoleName", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<int>("MentoredCandidatesId")
                        .HasColumnType("integer");

                    b.Property<int>("MentorsId")
                        .HasColumnType("integer");

                    b.HasKey("MentoredCandidatesId", "MentorsId");

                    b.HasIndex("MentorsId");

                    b.ToTable("CandidateMentor", (string)null);
                });

            modelBuilder.Entity("UserUser1", b =>
                {
                    b.Property<int>("HRCandidatesId")
                        .HasColumnType("integer");

                    b.Property<int>("HRsId")
                        .HasColumnType("integer");

                    b.HasKey("HRCandidatesId", "HRsId");

                    b.HasIndex("HRsId");

                    b.ToTable("CandidateHR", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AccountCreationToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "Candidate")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.AccountCreationToken", "CandidateId");

                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("Candidate");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.Entities.CandidateProcess", b =>
                {
                    b.HasOne("Domain.Entities.User", "Candidate")
                        .WithMany("CandidateProcesses")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.Feedback", b =>
                {
                    b.HasOne("Domain.Entities.User", "Candidate")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Domain.Entities.HRInfo", b =>
                {
                    b.HasOne("Domain.Entities.User", "HR")
                        .WithOne("HRInfo")
                        .HasForeignKey("Domain.Entities.HRInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HR");
                });

            modelBuilder.Entity("Domain.Entities.OnboardingAccessRequest", b =>
                {
                    b.HasOne("Domain.Entities.User", "Candidate")
                        .WithOne("OnboardingAccessRequest")
                        .HasForeignKey("Domain.Entities.OnboardingAccessRequest", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Teams")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId");

                    b.Navigation("Department");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.UserAuthToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("AuthToken")
                        .HasForeignKey("Domain.Entities.UserAuthToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserContactInfo", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("Candidates")
                        .HasForeignKey("CityId");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("ContactInfo")
                        .HasForeignKey("Domain.Entities.UserContactInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MentoredCandidatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MentorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser1", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HRCandidatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HRsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AuthToken");

                    b.Navigation("CandidateProcesses");

                    b.Navigation("ContactInfo");

                    b.Navigation("Feedbacks");

                    b.Navigation("HRInfo");

                    b.Navigation("OnboardingAccessRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
